// 公共(通用) message 定义 - 被【嵌套】使用

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: common_messages.proto

// protobuf 的包名，不是 Go 的。
// 在 hello_messages.proto 就得以 common.BaseResponse 包名形式嵌入

package protobuf_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 基础响应
type BaseResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 业务是否成功
	IsOk bool `protobuf:"varint,1,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
	// 业务状态码: 默认0, 其它公共状态码待定义, 可参考http状态码.
	Code int64 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	// 信息: 例如错误信息, 或者其他提示语
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_common_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_common_messages_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResponse) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

func (x *BaseResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_common_messages_proto protoreflect.FileDescriptor

const file_common_messages_proto_rawDesc = "" +
	"\n" +
	"\x15common_messages.proto\x12\x06common\"Q\n" +
	"\fBaseResponse\x12\x13\n" +
	"\x05is_ok\x18\x01 \x01(\bR\x04isOk\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessageB\x1eZ\x1c../protobuf_gen;protobuf_genb\x06proto3"

var (
	file_common_messages_proto_rawDescOnce sync.Once
	file_common_messages_proto_rawDescData []byte
)

func file_common_messages_proto_rawDescGZIP() []byte {
	file_common_messages_proto_rawDescOnce.Do(func() {
		file_common_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_messages_proto_rawDesc), len(file_common_messages_proto_rawDesc)))
	})
	return file_common_messages_proto_rawDescData
}

var file_common_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_messages_proto_goTypes = []any{
	(*BaseResponse)(nil), // 0: common.BaseResponse
}
var file_common_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_messages_proto_init() }
func file_common_messages_proto_init() {
	if File_common_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_messages_proto_rawDesc), len(file_common_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_messages_proto_goTypes,
		DependencyIndexes: file_common_messages_proto_depIdxs,
		MessageInfos:      file_common_messages_proto_msgTypes,
	}.Build()
	File_common_messages_proto = out.File
	file_common_messages_proto_goTypes = nil
	file_common_messages_proto_depIdxs = nil
}
