// hello 服务定义

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: hello_services.proto

package protobuf_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_hello_services_proto protoreflect.FileDescriptor

const file_hello_services_proto_rawDesc = "" +
	"\n" +
	"\x14hello_services.proto\x12\x05hello\x1a\x14hello_messages.proto2\x87\x01\n" +
	"\x05Hello\x127\n" +
	"\bSayHello\x12\x13.hello.HelloRequest\x1a\x14.hello.HelloResponse\"\x00\x12E\n" +
	"\x14SayHelloServerStream\x12\x13.hello.HelloRequest\x1a\x14.hello.HelloResponse\"\x000\x01B\x1eZ\x1c../protobuf_gen;protobuf_genP\x00b\x06proto3"

var file_hello_services_proto_goTypes = []any{
	(*HelloRequest)(nil),  // 0: hello.HelloRequest
	(*HelloResponse)(nil), // 1: hello.HelloResponse
}
var file_hello_services_proto_depIdxs = []int32{
	0, // 0: hello.Hello.SayHello:input_type -> hello.HelloRequest
	0, // 1: hello.Hello.SayHelloServerStream:input_type -> hello.HelloRequest
	1, // 2: hello.Hello.SayHello:output_type -> hello.HelloResponse
	1, // 3: hello.Hello.SayHelloServerStream:output_type -> hello.HelloResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hello_services_proto_init() }
func file_hello_services_proto_init() {
	if File_hello_services_proto != nil {
		return
	}
	file_hello_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hello_services_proto_rawDesc), len(file_hello_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hello_services_proto_goTypes,
		DependencyIndexes: file_hello_services_proto_depIdxs,
	}.Build()
	File_hello_services_proto = out.File
	file_hello_services_proto_goTypes = nil
	file_hello_services_proto_depIdxs = nil
}
