// hello 服务所用的 message 定义

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: hello_messages.proto

package protobuf_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求
type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_hello_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hello_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_hello_messages_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 响应
type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *BaseResponse          `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_hello_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hello_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_hello_messages_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetResult() *BaseResponse {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *HelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_hello_messages_proto protoreflect.FileDescriptor

const file_hello_messages_proto_rawDesc = "" +
	"\n" +
	"\x14hello_messages.proto\x12\x05hello\x1a\x15common_messages.proto\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"W\n" +
	"\rHelloResponse\x12,\n" +
	"\x06result\x18\x01 \x01(\v2\x14.common.BaseResponseR\x06result\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB\x1eZ\x1c../protobuf_gen;protobuf_genb\x06proto3"

var (
	file_hello_messages_proto_rawDescOnce sync.Once
	file_hello_messages_proto_rawDescData []byte
)

func file_hello_messages_proto_rawDescGZIP() []byte {
	file_hello_messages_proto_rawDescOnce.Do(func() {
		file_hello_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hello_messages_proto_rawDesc), len(file_hello_messages_proto_rawDesc)))
	})
	return file_hello_messages_proto_rawDescData
}

var file_hello_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hello_messages_proto_goTypes = []any{
	(*HelloRequest)(nil),  // 0: hello.HelloRequest
	(*HelloResponse)(nil), // 1: hello.HelloResponse
	(*BaseResponse)(nil),  // 2: common.BaseResponse
}
var file_hello_messages_proto_depIdxs = []int32{
	2, // 0: hello.HelloResponse.result:type_name -> common.BaseResponse
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hello_messages_proto_init() }
func file_hello_messages_proto_init() {
	if File_hello_messages_proto != nil {
		return
	}
	file_common_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hello_messages_proto_rawDesc), len(file_hello_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hello_messages_proto_goTypes,
		DependencyIndexes: file_hello_messages_proto_depIdxs,
		MessageInfos:      file_hello_messages_proto_msgTypes,
	}.Build()
	File_hello_messages_proto = out.File
	file_hello_messages_proto_goTypes = nil
	file_hello_messages_proto_depIdxs = nil
}
