
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      - link: "mysql:root:mysql80Root332211@tcp(127.0.0.1:33888)/goframe_quick?charset=utf8mb4"
        # descriptionTag: 生成的entity代码文件增加字段描述到description标签中
        descriptionTag: true

  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app